version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    groups:
      frontend-production:
        dependency-type: production
        patterns:
          - "*"
      frontend-development:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: composer
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/Paris
    groups:
      backend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Paris
    groups:
      github-actions:
        patterns:
          - "*"
